### ISSUE TITLE
precompiled not first include error

### ISSUE THREAD

**Issue by Enhex** [jimon/premake-ninja#31]
generating two "-include precompiled.h" args,
once in CFLAGS & CXXFLAGS
and once in rule cc/cxx's `command`.

this causes compilation error:
```
clang-15: warning: precompiled header 'obj/precompiled.h.gch' was ignored because '-include obj/precompiled.h' is not first '-include'
clang-15: warning: argument unused during compilation: '-MD' [-Wunused-command-line-argument]
<built-in>:2:10: fatal error: 'obj/precompiled.h' file not found
```

removing `-include obj/precompiled.h` from `command` fixes this problem.

**Comment by Jarod42** [comment]
Warning about `-MD` just fixed by https://github.com/jimon/premake-ninja/commit/50798a57a070b7dd9a0340ea88ca0202cb98a3c5

About pch, the test projects https://github.com/Jarod42/premake-sample-projects/tree/master/projects/project-03-pch and https://github.com/Jarod42/premake-sample-projects/tree/master/projects/project-forceincludes
pass successfully with ninja (both gcc/clang and even msvc :-) ).

Can you show your (simplified) premake5.lua?

**Comment by Enhex** [comment]
looking at my code compared to these tests i use both `pchheader` and `forceincludes`:
```
pchheader "precompiled.h"
pchsource "src/precompiled.cpp"
forceincludes{ precompiled.h" }
```

if i recall correctly i did it few years ago because using only one of them will cause either GCC or MSVC to not work.
I'll need to test it again and report back.

**Comment by Jarod42** [comment]
From what I can see from the tests, 
- premake4 has some issues, at least with codelite (which doesn't add the `forceinclude`),
and I don't have CI for premake4 with msvc, so, maybe similar issues (but as msvc is first citizen in premake, I doubt it was problematic). but premake4 is old anyway ;-)
- In premake5, only xcode4 has issues with pch.

**Comment by Enhex** [comment]
to narrow down the checking I got the error on Linux with premake5 and gmake2
